format = 1
name = "47ter"
mbid = "d3812f13-0962-42a8-bbcd-0e64c873b2eb"
spotify = "0aXaZj4wB5jLF2E2d8WEVi"

tags = ["hip-hop", "pop-rap", "fr"]

tops = [
  "Côte Ouest",
  "Superstar",
  "On avait dit",
  "Soleil noir",
  "L'adresse",
]

links = [
  { to = "bigflo-and-oli", type = "similar" },
]
