format = 1
name = "Angus & Julia Stone"
mbid = "69837400-8e31-4949-aac2-00b46b4df126"
spotify = "4tvKz56Tr39bkhcQUTO0Xr"
begin = "2006"
origin = "Sydney"

tags = ["folk", "indie-pop", "au", "2000s"]

tops = [
  "Big Jet Plane (Radio Edit)",
  "The Start",
  "Big Jet Plane",
  "Karaoke Bar",
  "Strangely Strangely",
]

links = [
  { to = "cat-power", type = "similar" },
  { to = "damien-rice", type = "similar" },
  { to = "jose-gonzalez", type = "similar" },
  { to = "iron-and-wine", type = "similar" },
]
