format = 1
name = "Arno"
mbid = "03a82b66-d021-4754-aca2-399d51ee6199"
spotify = "0pJz4IBnZkfgJFTrqBl3ZQ"
begin = "1949"
end = "2022"
origin = "Oostende"

tags = ["rock", "be"]

tops = [
  "Les yeux de ma mère (en concert)",
  "Les paradis perdus",
  "Les filles du bord de mer",
  "Pauvres Diables - Vous les femmes",
  "Ils ont changé ma chanson",
]

links = [
  { to = "arthur-h", type = "similar" },
  { to = "alain-bashung", type = "similar" },
  { to = "brigitte-fontaine", type = "similar" },
  { to = "miossec", type = "similar" },
]
