format = 1
name = "Beirut"
mbid = "0af78501-5647-4c18-9a0d-66ac8789e13b"
spotify = "6pmxr66tMAePxzOLfjGNcX"
begin = "2006"
origin = "Santa Fe"

tags = ["indie-folk", "chamber-pop", "contemporary-folk", "indie-pop", "us", "2000s"]

tops = [
  "Nantes",
  "A Sunday Smile",
  "Gallipoli",
  "No No No",
  "Santa Fe",
]

links = [
  { to = "cat-power", type = "similar" },
  { to = "girls-in-hawaii", type = "similar" },
  { to = "devendra-banhart", type = "similar" },
  { to = "syd-matters", type = "similar" },
]
