format = 1
name = "Bilal"
mbid = "260097c7-d628-4a3f-966f-956ea430c0d8"
spotify = "6mmfF4ERGkMvAQ1VTzvRgX"
begin = "1979"
origin = "Philadelphia"

tags = ["neo-soul", "us"]

tops = [
  "Soul Sista",
  "200 degrés",
  "Fast Lane (Remix)",
  "Ghetto Walkin'",
  "For U",
]
