format = 1
name = "Billy Nomates"
mbid = "a9b2d360-0ebc-47d9-9870-a7e7b225b365"
spotify = "0QJaBD8Piha8IEwKtNpBOB"

tags = ["indie-rock", "post-punk", "uk"]

tops = [
  "The Test",
  "Nothin Worth Winnin",
  "Life's Unfair",
  "Override",
  "Metalhorse",
]

links = [
  { to = "sleaford-mods", type = "similar" },
  { to = "idles", type = "similar" },
]
