format = 1
name = "Blundetto"
mbid = "18bca353-d128-4503-960e-05ee82b3b909"
spotify = "3bWxjvKUe8YV0VkI5d3I1Y"

tags = ["dub", "electronic", "reggae", "soul", "fr"]

tops = [
  "Groenland",
  "Calypso Blues (feat. Blundetto & Biga Ranx)",
  "País Azucar",
  "Lampadaires",
  "To Be A Man",
]

links = [
  { to = "biga-ranx", type = "similar" },
]
