format = 1
generated = true
name = "Boo"
mbid = "a15ba7c3-e02e-440b-bc7e-cc60c328e34a"
spotify = "75aF8TBGAxDZlcFPDEhIIK"
begin = "1998"

tags = ["cz", "90s"]

tops = [
  "The Sea",
  "Don't Speak to Me",
  "Stones",
  "Listen",
  "The Answer",
]
