format = 1
name = "Brutus"
mbid = "90b8f9f7-dfda-409c-a9dc-391bd0de6d8a"
spotify = "7m63GptZSke3jGqCxR4rom"
begin = "2014"
origin = "Leuven"

tags = ["post-hardcore", "post-metal", "post-rock", "be", "2010s"]

tops = [
  "Paradise",
  "War (Live in Brussels)",
  "Liar (Live in Brussels)",
  "Sugar Dragon (Live in Brussels)",
  "What Have We Done (Live at Pukkelpop)",
]
