format = 1
name = "Buzzcocks"
mbid = "31e9c35b-2675-4632-8596-f9bd9286f6c8"
spotify = "2DxlS3lTLFIq70S7ap5H3y"
begin = "1976"
origin = "Bolton"

tags = ["power-pop", "punk-rock", "pop-punk", "post-punk", "uk", "70s"]

tops = [
  "Ever Fallen in Love (With Someone You Shouldn't've)?",
  "What Do I Get?",
  "Fast Cars",
  "Why Can't I Touch It?",
  "Boredom",
]

links = [
  { to = "the-clash", type = "similar" },
]
