format = 1
name = "Caballero & JeanJass"
mbid = "09f03eb2-9c27-43ae-b5d1-43b9fbf9413b"
spotify = "1mMUzAMrNqoTHgtxA0dZi6"
begin = "2014"
origin = "Brussels"

tags = ["hip-hop", "be", "2010s"]

tops = [
  "Comic sans MS",
  "Les Tiktoks de Bardella",
  "Constellation",
  "Bae",
  "Panorama",
]
