format = 1
name = "Childish Gambino"
mbid = "7fb57fba-a6ef-44c2-abab-2fa3bdee607e"
spotify = "73sIBHcqh3Z3NyqHKZ7FOL"
begin = "1983"
origin = "Edwards Air Force Base"

tags = ["hip-hop", "contemporary-r-and-b", "neo-soul", "r-and-b", "us"]

tops = [
  "Les",
  "Redbone",
  "Heartbeat",
  "Me and Your Mama",
  "Letter Home",
]

links = [
  { to = "jaden", type = "similar" },
  { to = "sza", type = "scene", note = "même époque et pays, genres proches : contemporary-r-and-b, r-and-b" },
  { to = "justin-timberlake", type = "scene", note = "même époque et pays, genres proches : contemporary-r-and-b, r-and-b" },
]
