format = 1
name = "Dalle Béton"
mbid = "7ab6768e-bda0-4789-9cfb-bdaf062ff4a6"
spotify = "5U0wT5tqaSZK8cmOGdevd5"

tags = ["fr"]

tops = [
  "49.3",
  "Mange Ton Compost",
  "Doudoune Sans Manche",
  "Les aléas du vin nat",
  "Machine à Laver",
]
