format = 1
name = "Depeche Mode"
mbid = "8538e728-ca0b-4321-b7e5-cff6565dd4c0"
spotify = "762310PdDnwsDxAQxzQkfX"
begin = "1980"
origin = "Basildon"

tags = ["electronic", "synth-pop", "new-wave", "alternative-rock", "uk", "80s"]

tops = [
  "Enjoy the Silence",
  "Just Can't Get Enough",
  "Personal Jesus",
  "Never Let Me Down Again",
  "Shake the Disease",
]

links = [
  { to = "the-cure", type = "similar" },
  { to = "new-order", type = "similar" },
]
