format = 1
name = "Disiz"
mbid = "daba3096-88f2-4322-9b00-10938b0220b8"
spotify = "7rz6ZZErn5YFDteXKhyf3g"
begin = "1978"
origin = "Amiens"

tags = ["hip-hop", "fr"]

tops = [
  "melodrama",
  "RENCONTRE",
  "mAnIAc",
  "try try try (feat. Kid Cudi)",
  "amsterdam",
]

links = [
  { to = "romeo-elvis", type = "similar" },
  { to = "sopico", type = "similar" },
]
