format = 1
name = "Dominic Fike"
mbid = "e337c918-098f-418e-97a2-81dc224b1bf9"
spotify = "6USv9qhCn6zfxlBQIYJ9qs"
begin = "1995"
origin = "Naples"

tags = ["alternative-pop", "us"]

tops = [
  "Babydoll",
  "White Keys",
  "3 Nights",
  "Mama's Boy",
  "Photo ID",
]

links = [
  { to = "tame-impala", type = "similar" },
]
