format = 1
name = "Dyablo"
mbid = "35844999-6006-48d0-a414-22e9940ee2ec"

tags = []

tops = [
  "El Imperio",
  "Pecado Mortal",
  "El Juego de la Vida",
  "Toque de Guerra!!!",
  "City of Tha Padres",
]

links = [
  { to = "akwid", type = "audience" },
  { to = "jae-p", type = "audience" },
  { to = "kinto-sol", type = "audience" },
  { to = "kartel-de-las-calles", type = "audience" },
]
