format = 1
name = "Elliott Smith"
mbid = "03ad1736-b7c9-412a-b442-82536d63a5c4"
spotify = "2ApaG60P4r0yhBoDCGD8YG"
begin = "1969"
end = "2003"
origin = "Omaha"

tags = ["indie-folk", "indie-rock", "indie-pop", "acoustic-rock", "us"]

tops = [
  "Between The Bars",
  "Angeles",
  "Say Yes",
  "Miss Misery",
  "Waltz #2 (XO)",
]

links = [
  { to = "yo-la-tengo", type = "similar" },
  { to = "radiohead", type = "similar" },
  { to = "mazzy-star", type = "similar" },
  { to = "wilco", type = "similar" },
]
