format = 1
name = "Georges Bizet"
mbid = "9bd20e6a-b41d-4983-a5b6-c0ff849fa235"
spotify = "2D7RkvtKKb6E5UmbjQM1Jd"
begin = "1838"
end = "1875"
origin = "Paris"

tags = ["classical", "opera", "romantic-classical", "orchestral", "fr"]

tops = [
  "L'Arlésienne Suite No. 2 (Arr. Guiraud) : Bizet: L'Arlésienne Suite No. 2 (Arr. Guiraud): IV. Farandole",
  "La Habanera (Princess In the Bar Room) [After Bizet In Carmen]",
  "That's Love for You (After the Masquerade) [After G. Bizet \"Carmen\"]",
  "Carmen : Bizet: Carmen: Prelude. Allegro giocoso",
  "Carmen, Act II : Bizet: Carmen, Act II: Toreador's Song. Votre toast, je peux vous le rendre",
]
