format = 1
name = "Gorillaz"
mbid = "e21857d5-3256-4547-afb3-4b6ded592596"
spotify = "3AA28KZvwAUcZuOKwyblJQ"
begin = "1999"
origin = "Essex"

tags = ["electronic", "alternative-rock", "trip-hop", "hip-hop", "uk", "90s"]

tops = [
  "Feel Good Inc.",
  "Clint Eastwood",
  "On Melancholy Hill",
  "DARE (feat. Shaun Ryder & Roses Gabor)",
  "Rhinestone Eyes",
]

links = [
  { to = "the-strokes", type = "similar" },
  { to = "tame-impala", type = "similar" },
  { to = "arctic-monkeys", type = "similar" },
  { to = "phoenix", type = "similar" },
]
