format = 1
name = "Graham Coxon"
mbid = "fb56cc34-2ab1-4621-ac18-9bf2895e5f4f"
spotify = "7ueZp29tCNwjIj4yAMTEaC"
begin = "1969"
origin = "Rinteln"

tags = ["alternative-rock", "contemporary-folk", "experimental-rock", "indie-rock", "uk"]

tops = [
  "Walking All Day",
  "Billy Says",
  "Yoga Town",
  "Meaner Than The Sea",
  "Parasite",
]

links = [
  { to = "blur", type = "member" },
  { to = "kevin-morby", type = "similar" },
]
