format = 1
name = "Guilhem Valaye"
mbid = "76ccbb78-91df-49bf-9f18-31adae586786"
spotify = "7uTkqqOQNvjARy45pUraKA"

tags = []

tops = [
  "FORT ADAMO",
  "De nerfs et de bosses",
  "RIEUPEYROUX",
  "KOALA",
  "REVIENS-TOI",
]

links = [
  { to = "bertrand-belin", type = "similar" },
]
