format = 1
name = "Hariprasad Chaurasia"
mbid = "d2326d39-1287-42d7-80ba-71663b9169d3"
spotify = "7CozfB3IEACZpAelpwkUon"
begin = "1938"
origin = "Allahabad"

tags = ["hindustani-classical", "indian-classical", "in"]

tops = [
  "Folktune",
  "Raga Madhuvanti",
  "Abhogi",
  "Raga Durga",
  "Breath Of Life",
]
