format = 1
name = "J Balvin"
mbid = "5bdeb32d-56a5-4b6d-a768-264101fa0a0a"
spotify = "4veAf5hFxUDeWaeyjfOVT5"
begin = "1985"
origin = "Medellín"

tags = ["reggaeton", "hip-hop", "latin", "latin-pop", "co"]

tops = [
  "Say My Name",
  "Loco Contigo",
  "Azul",
  "LA CANCIÓN",
  "I Like It",
]

links = [
  { to = "ozuna", type = "similar" },
  { to = "daddy-yankee", type = "similar" },
  { to = "farruko", type = "similar" },
]
