format = 1
name = "Jabberwocky"
mbid = "2b82eaa2-8df1-4caa-9c3a-20554728a31e"
spotify = "7xfdx6PiB50V9VWI4Mq70R"

tags = ["nl"]

tops = [
  "Letter to the sea",
  "Heart of Wolves",
  "Echoes",
  "Howls",
  "Daydream",
]
