format = 1
name = "JoeyStarr"
mbid = "20c6e313-e93d-4972-a164-403447bbe001"
spotify = "5q3WViYe7mEvzU9CY6lixh"
begin = "1967"
origin = "Saint-Denis"

tags = ["hip-hop", "fr"]

tops = [
  "Outro",
  "Grimpe",
  "Zicmu: Intro",
  "La poursuite des chiens",
  "Présentation des personnages",
]
