format = 1
name = "José González"
mbid = "cd8c5019-5d75-4d5c-bc28-e1e26a7dd5c8"
spotify = "6xrCU6zdcSTsG2hLrojpmI"
begin = "1978"
origin = "Gothenburg"

tags = ["folk", "singer-songwriter", "folk-rock", "indie-folk", "se"]

tops = [
  "Let It Carry You (Brandt Brauer Frick Remix)",
  "Heartbeats (Logic1000 Rework)",
  "Broken Arrows (Portico Quartet Rework)",
  "Futures (Carl Craig Remix)",
  "Analog Sex",
]
