format = 1
name = "Kelly Rowland"
mbid = "31bea673-d23a-4889-8da1-7cb040863268"
spotify = "3AuMNF8rQAKOzjYppFNAoB"
begin = "1981"
origin = "Atlanta"

tags = ["contemporary-r-and-b", "pop", "dance-pop", "electro-house", "us"]

tops = [
  "Commander",
  "Work (Freemasons Radio Edit)",
  "Motivation",
  "Hitman",
  "Like This (feat. Eve) (Album Version)",
]

links = [
  { to = "destinys-child", type = "member", note = "membre (1990–…)" },
  { to = "beyonce", type = "similar" },
  { to = "justin-timberlake", type = "similar" },
  { to = "jamie-foxx", type = "similar" },
]
