format = 1
name = "La Dispute"
mbid = "2ec89bcc-5bf9-4d2a-ac5e-44b7496d115a"
spotify = "7lQKE6HaKQcCsgLRMhsh5W"
begin = "2004"
origin = "Grand Rapids"

tags = ["post-hardcore", "spoken-word", "emo", "screamo", "us", "2000s"]

tops = [
  "Andria",
  "I Shaved My Head",
  "Said the King to the River",
  "Damaged Goods",
  "New Storms for Older Lovers",
]
