format = 1
name = "Les Ogres de Barback"
mbid = "a9a7819b-8c6a-4b9a-a3e9-cad0471963df"
spotify = "3avSMklPuyXhcT5Smt1h7G"
begin = "1994"
origin = "Île-de-France"

tags = ["chanson-francaise", "fr", "90s"]

tops = [
  "Au café du canal",
  "Mam'selle bulle",
  "Rue de panam (Chant)",
  "Les cigales (Live 2017)",
  "Gbaou Gbaou (Live tout en commun)",
]

links = [
  { to = "les-hurlements-dleo", type = "similar" },
  { to = "la-rue-ketanou", type = "similar" },
  { to = "tetes-raides", type = "similar" },
  { to = "mano-solo", type = "similar" },
]
