format = 1
name = "Les Hurlements d’Léo"
mbid = "8112488e-0da3-4e2e-b71d-c17630e94f69"
spotify = "5WclEPgvoYK28a034NNa8s"
begin = "1995"
origin = "France"

tags = ["rock", "fr", "90s"]

tops = [
  "Les cigales (Live 2017)",
  "Les mots (Live 2017)",
  "Poil aux yeux (Live 2017)",
  "Jojo (Live 2017)",
  "Le café des jours heureux (Live 2017)",
]

links = [
  { to = "les-ogres-de-barback", type = "similar" },
  { to = "la-rue-ketanou", type = "similar" },
  { to = "tetes-raides", type = "similar" },
]
