format = 1
name = "Loïc Lantoine"
mbid = "9fa5cbb1-e5a7-447f-b4ed-01c213e110e4"
spotify = "1zJwk8m4TL8v36ac3PHqU6"
origin = "Lille"

tags = ["fr"]

tops = [
  "Au café du canal",
  "Côté Punk",
  "La Maison Ronchonchon",
  "Pierrot",
  "Le bourg de la Grognardière",
]

links = [
  { to = "mano-solo", type = "similar" },
  { to = "tetes-raides", type = "similar" },
  { to = "lojo", type = "similar" },
  { to = "brigitte-fontaine", type = "similar" },
]
