format = 1
name = "Maceo & the Macks"
mbid = "6bd34fc8-84de-4c32-a2d5-1f43d148a177"
spotify = "0rDIqnqwAmDPL1gyzoFH9y"

tags = ["us"]

tops = [
  "Cross The Tracks (We Better Go Back)",
  "Parrty (Pt. 1)",
]
