format = 1
name = "Manu Chao"
mbid = "7570a0dd-5a67-401b-b19a-261eee01a284"
spotify = "6wH6iStAh4KIaWfuhf0NYM"
begin = "1961"
origin = "Paris"

tags = ["folk", "latin", "reggae", "ska", "fr"]

tops = [
  "Me Gustas Tu",
  "Clandestino",
  "Bongo Bong",
  "Je ne t'aime plus",
  "Tu Te Vas",
]

links = [
  { to = "mano-negra", type = "member" },
  { to = "massilia-sound-system", type = "similar" },
  { to = "blundetto", type = "similar" },
]
