format = 1
name = "McFly et Carlito"
mbid = "d7e59713-d000-4b54-8e11-5cc086aa2753"
spotify = "2DNfUNwenBiLLGMc4vQGei"

tags = ["fr"]

tops = [
  "Désolé pour hier soir XXV",
  "I Wanna Dance Latina",
  "Ok Boomer",
  "Je me souviens",
  "I Wanna Dance Latina (Extended Mix)",
]

links = [
  { to = "squeezie", type = "similar" },
  { to = "joyca", type = "similar" },
  { to = "norman", type = "similar" },
]
