format = 1
name = "Naïve New Beaters"
mbid = "b98c9e55-6964-4c62-9804-bd325bd15d70"
spotify = "0xW1QQBD5O09HptO2fEaI4"
begin = "2004"

tags = ["pop-rap", "fr", "2000s"]

tops = [
  "Heal Tomorrow",
  "Dancing",
  "Love Scares",
  "Montecristo",
  "Live Good",
]

links = [
  { to = "metronomy", type = "audience" },
  { to = "phoenix", type = "audience" },
  { to = "hot-chip", type = "audience" },
  { to = "the-rapture", type = "audience" },
  { to = "ttc", type = "scene", note = "Playful 2000s French rap over electro beats." },
]
