format = 1
generated = true
name = "Noob"
mbid = "d3ded85b-5613-48ac-8e02-493a15ba4599"
spotify = "3p2cynbpnQqIukLKI5AJ33"

tags = ["fr"]

tops = [
  "Pas volé",
  "Poumon",
  "Extreme Compote",
  "7 vies",
  "Wild",
]

links = [
  { to = "vitalic", type = "similar" },
  { to = "modeselektor", type = "similar" },
  { to = "birdy-nam-nam", type = "similar" },
  { to = "sebastian", type = "similar" },
]
