format = 1
name = "Paul McCartney"
mbid = "ba550d0e-adac-4864-b88b-407cab5e76af"
spotify = "7wcH6naXfssACcXRregV1H"
begin = "1942"
origin = "Walton"

tags = ["pop", "pop-rock", "rock", "rock-and-roll", "uk"]

tops = [
  "FourFiveSeconds",
  "Say Say Say",
  "Live And Let Die",
  "Let Me Roll It",
  "Let 'Em In",
]

links = [
  { to = "the-beatles", type = "member", note = "membre (1960–1970)" },
  { to = "wings", type = "member", note = "membre (1971–1981)" },
  { to = "john-lennon", type = "similar" },
  { to = "david-bowie", type = "similar" },
  { to = "eagles", type = "similar" },
  { to = "eric-clapton", type = "similar" },
]
