format = 1
name = "PJ Harvey"
mbid = "e795e03d-b5d5-4a5f-834d-162cfb308a2c"
spotify = "12VaqyEhgwDRuFfEqbnrpz"
begin = "1969"
origin = "Bridport"

tags = ["alternative-rock", "indie-rock", "art-rock", "folk-rock", "uk"]

tops = [
  "Down By The Water",
  "This Mess We're In",
  "This Is Love",
  "Good Fortune",
  "Voyager",
]

links = [
  { to = "nick-cave-and-the-bad-seeds", type = "similar" },
  { to = "the-kills", type = "similar" },
  { to = "the-divine-comedy", type = "similar" },
  { to = "girls-in-hawaii", type = "similar" },
]
