format = 1
name = "Rendez-Vous"
mbid = "818ca074-01d4-4302-94f3-57192b22bdf3"
spotify = "4a118edzJsiImCyPCZk6mY"
begin = "2012"
origin = "Paris"

tags = ["fr", "2010s"]

tops = [
  "Sentimental Animal",
  "The Others",
  "Plasticity",
  "Downcast",
  "Euroshima",
]
