format = 1
name = "Skread"
mbid = "64a650d2-9b30-4d9b-bc09-e6a2612f60c7"
spotify = "6BbceEVcjow8mhQPYK3eBK"
begin = "1981"
origin = "Hérouville-Saint-Clair"

tags = ["hip-hop", "instrumental-hip-hop", "fr"]

tops = [
  "J'Y PENSE",
  "GRA GRA BOOM (feat. Skread)",
  "A.V.S.D",
]
