format = 1
name = "Sopico"
mbid = "e2e98f64-4b5b-497f-8534-7da6622361be"
spotify = "01fkQiYuBZt16vQ8iRIc7g"
begin = "1991"
origin = "17e arrondissement de Paris"

tags = ["hip-hop", "fr"]

tops = [
  "Comme ça (feat. Sopico)",
  "Unplugged #4: La nuit",
  "Slide",
  "Une clope après l'amour",
  "Sandman (Remix)",
]
