format = 1
name = "SZA"
mbid = "272989c8-5535-492d-a25c-9f58803e027f"
spotify = "7tYKF4w9nC0nq9CsPZTHyP"
begin = "1989"
origin = "St. Louis"

tags = ["contemporary-r-and-b", "electronic", "r-and-b", "alternative-r-and-b", "us"]

tops = [
  "All The Stars (From \"Black Panther: The Album\")",
  "Kill Bill",
  "Kiss Me More (feat. SZA)",
  "TELEKINESIS (feat. SZA & Future)",
  "Snooze",
]
