format = 1
name = "Talking Heads"
mbid = "a94a7155-c79d-4409-9fcf-220cb0e4dc3a"
spotify = "2x9SpqnPi8rlE9pjHBwmSC"
begin = "1974"
end = "1991"
origin = "New York"

tags = ["new-wave", "post-punk", "art-punk", "art-pop", "us", "70s"]

tops = [
  "Psycho Killer",
  "This Must Be the Place (Naive Melody)",
  "Once in a Lifetime",
  "Burning Down the House",
  "This Must Be the Place (Naive Melody) (Live)",
]

links = [
  { to = "tina-weymouth", type = "member", note = "membre (1975–1991)" },
  { to = "david-bowie", type = "similar" },
  { to = "the-b-52s", type = "similar" },
  { to = "the-clash", type = "similar" },
  { to = "the-cure", type = "similar" },
]
