format = 1
name = "Têtes Raides"
mbid = "739162d3-8f9d-4710-8fe1-a73e59690506"
spotify = "5e6HjLNS1AnsfACv1g6yVb"
begin = "1984"
origin = "Paris"

tags = ["alternative-rock", "folk-rock", "fr", "80s"]

tops = [
  "L'identité",
  "Je chante",
  "Saint-Vincent",
  "Ginette (Corps de mots)",
  "Gino",
]

links = [
  { to = "mano-solo", type = "similar" },
  { to = "les-ogres-de-barback", type = "similar" },
  { to = "les-hurlements-dleo", type = "similar" },
  { to = "la-rue-ketanou", type = "similar" },
]
