format = 1
name = "The Rolling Stones"
mbid = "b071f9fa-14b0-4217-8e97-eb41da73f598"
spotify = "22bE4uQ6baNwSHPVcDxLCe"
begin = "1962"
origin = "London"

tags = ["rock", "blues-rock", "classic-rock", "psychedelic-rock", "uk", "60s"]

tops = [
  "Start Me Up",
  "Sympathy For The Devil",
  "(I Can't Get No) Satisfaction (Mono)",
  "Miss You",
  "Wild Horses (2009 Mix)",
]

links = [
  { to = "the-who", type = "similar" },
  { to = "the-beatles", type = "similar" },
  { to = "david-bowie", type = "similar" },
  { to = "bob-dylan", type = "similar" },
]
