format = 1
name = "The Great Bertholinis"
mbid = "82335a24-6fa0-46be-befe-2a65dddeb23d"
spotify = "1gUfn4t4GzgwunzkJODHCE"

tags = []

tops = [
  "Hey Pal",
  "Trembling Hands Breakdown",
  "All Dead",
  "I'm Still A Door",
  "Run To Hide",
]
