format = 1
name = "Thom Yorke"
mbid = "8ed2e0b3-aa4c-4e13-bec3-dc7393ed4d6b"
spotify = "4CvTDPKA6W06DRfBnZKrau"
begin = "1968"
origin = "Wellingborough"

tags = ["electronic", "alternative-rock", "ambient", "ambient-pop", "uk"]

tops = [
  "Hearing Damage",
  "Suspirium",
  "Black Swan",
  "Analyse",
  "Unmade",
]

links = [
  { to = "radiohead", type = "member" },
  { to = "archive", type = "similar" },
  { to = "pj-harvey", type = "similar" },
  { to = "bjork", type = "similar" },
  { to = "king-hannah", type = "similar" },
]
