format = 1
name = "Tinariwen"
mbid = "5c98fc12-be83-4246-ae5b-2184192913b9"
spotify = "2sf2owtFSCvz2MLfxmNdkb"
begin = "1982"
origin = "Kidal"

tags = ["desert-blues", "folk", "traditional-pop", "ml", "80s"]

tops = [
  "Sastanàqqàm",
  "Erghad Afewo",
  "Nànnuflày",
  "Tiwàyyen",
  "Sagherat Assani (feat. Sulaf)",
]

links = [
  { to = "ali-farka-toure", type = "similar" },
]
