format = 1
name = "Traband"
mbid = "2aa9cdd4-6337-4df0-bfb5-b2e9defad219"
spotify = "4M6ui8P7kQmxRhrsPihC6R"
begin = "1995"

tags = ["cz", "90s"]

tops = [
  "Cernej Pasažér",
  "Sáro! (Sara!)",
  "Kolotoc",
  "Vlaštovky",
  "Na sirem mori",
]
