format = 1
name = "Troublemakers"
mbid = "adae038f-f39b-4ed3-bca8-dd1044a60f7c"
spotify = "7t9HJhKr56Fv4HgCLm18vh"
origin = "Marseille"

tags = ["easy-listening", "electronic", "fr"]

tops = [
  "Get Misunderstood",
  "Street Preacher",
  "Too Old To Die",
]

links = [
  { to = "smooth", type = "audience" },
  { to = "dj-cam", type = "audience" },
  { to = "nightmares-on-wax", type = "audience" },
  { to = "the-herbaliser", type = "audience" },
]
