format = 1
name = "Troublemakers"
mbid = "adae038f-f39b-4ed3-bca8-dd1044a60f7c"
spotify = "7t9HJhKr56Fv4HgCLm18vh"
origin = "Marseille"

tags = ["easy-listening", "electronic", "fr"]

tops = [
  "Lemon",
  "Allen Fresh",
  "Everyday Is an Extension of Yesterday",
  "County Farm",
  "V72",
]

links = [
  { to = "smooth", type = "similar" },
  { to = "dj-cam", type = "similar" },
  { to = "nightmares-on-wax", type = "similar" },
  { to = "the-herbaliser", type = "similar" },
]
