format = 1
name = "Vanessa Paradis"
mbid = "46193c80-959a-499d-b42f-f33ba7b9b18e"
spotify = "1FmxE030Xe2H8Bn9bdv6Pd"
begin = "1972"
origin = "Saint-Maur-des-Fossés"

tags = ["pop", "pop-rock", "chanson-francaise", "pop-soul", "fr"]

tops = [
  "Dès que j'te vois",
  "Divine idylle",
  "Les épines du coeur",
  "Mi Amor",
  "Joe le taxi",
]

links = [
  { to = "etienne-daho", type = "similar" },
  { to = "m", type = "similar" },
  { to = "louis-chedid", type = "similar" },
  { to = "les-innocents", type = "similar" },
]
