format = 1
name = "Vinicio Capossela"
mbid = "5115929f-f133-47b4-bf1c-8a0df582ce23"
spotify = "6FlxhoUGATC40TALMesaFM"
begin = "1965"
origin = "Hannover"

tags = ["singer-songwriter", "folk", "it"]

tops = [
  "Che cossè l'amor",
  "Si è spento il sole",
  "Non è l'amore che va via",
  "Con una rosa",
  "Ovunque proteggi",
]
