format = 1
name = "XXXTENTACION"
mbid = "61af87f4-16ee-4431-8504-cc06187079fb"
spotify = "15UsOTVnJzReFVN1VCnxy4"
begin = "1998"
end = "2018"
origin = "Plantation"

tags = ["trap", "hip-hop", "emo-rap", "trap-metal", "us"]

tops = [
  "Moonlight",
  "Falling Down (Bonus Track)",
  "Hope",
  "SAD!",
  "Fuck Love",
]

links = [
  { to = "juice-wrld", type = "similar" },
  { to = "iann-dior", type = "similar" },
  { to = "kodak-black", type = "similar" },
]
