format = 1
name = "Zebda"
mbid = "8eebc0a9-653e-4b12-bfb6-471a95f8cf73"
spotify = "0eOdRJIL6L8AInJLre2uIP"
begin = "1985"
origin = "Toulouse"

tags = ["boom-bap", "conscious-hip-hop", "hip-hop", "political-hip-hop", "fr", "80s"]

tops = [
  "Tomber la chemise",
  "Oualalaradime",
  "Y' a pas d'arrangement",
  "Tombés des nues",
  "Le bruit et l'odeur",
]

links = [
  { to = "les-ogres-de-barback", type = "audience" },
  { to = "fabulous-trobadors", type = "audience" },
  { to = "tetes-raides", type = "audience" },
  { to = "la-rue-ketanou", type = "audience" },
]
