plays = 4.825558615190458
last = "2026-09-24"
weight = 1.0

[tops.Again]
plays = 1.0
last = "2026-09-15"

[tops."City Walls"]
plays = 1.0
last = "2026-09-10"

[tops."Here - 2024 Remaster"]
plays = 1.0
last = "2026-09-14"

[tops."Look At Us"]
plays = 1.0
last = "2026-09-24"

[tops."So Far From Losing You"]
plays = 1.0
last = "2026-09-10"
