plays = 3.0
last = "2026-09-10"
weight = 1.0

[tops."Charmless Man"]
plays = 1.0
last = "2026-09-10"

[tops."Country House"]
plays = 1.0
last = "2026-09-10"

[tops."Girls & Boys"]
plays = 1.0
last = "2026-09-10"
liked = true
