plays = 12.498755575170062
last = "2026-09-21"
weight = 1.0

[tops."In This Hole"]
plays = 2.9699729783527866
last = "2026-09-15"
liked = true

[tops."Lived in Bars"]
plays = 1.0
last = "2026-09-08"

[tops.Manhattan]
plays = 1.0
last = "2026-09-08"

[tops."Metal Heart"]
plays = 1.0
last = "2026-09-07"

[tops."Nude As the News"]
plays = 3.87363777663687
last = "2026-09-21"
liked = true

[tops.Say]
plays = 1.0
last = "2026-09-14"

[tops."Sea of Love"]
plays = 1.0
last = "2026-09-07"

[tops."The Greatest"]
plays = 1.0
last = "2026-09-07"
