plays = 3.0
last = "2026-09-07"
weight = 1.0

[tops."Bord de mer"]
plays = 1.0
last = "2026-09-07"
liked = true

[tops.Happiness]
plays = 1.0
last = "2026-09-07"

[tops."Quattro stagioni"]
plays = 1.0
last = "2026-09-07"
