plays = 2.0
last = "2026-10-10"
weight = 1.4285714626312256

[tops.Apocalypse]
plays = 1.0
last = "2026-10-10"

[tops.Sweet]
plays = 1.0
last = "2026-10-10"

[connections]
king-hannah = 3
luna = 4
mazzy-star = 4

[declined]
m83 = "2026-10-10"
