plays = 3.0
last = "2026-09-07"
weight = 1.0

[tops.Immortels]
plays = 1.0
last = "2026-09-07"

[tops."Le Courage des oiseaux"]
plays = 1.0
last = "2026-09-07"

[tops."Le travail"]
liked = true

[tops."Rendez-nous la lumière"]
plays = 1.0
last = "2026-09-07"
