plays = 1.0
last = "2026-09-09"
weight = 1.0

[tops."Aujourd'hui maintenant"]
plays = 1.0
last = "2026-09-09"
liked = true

[tops.Deux]
liked = true

[tops."Entre voisins"]
liked = true

[tops.Essayer]
liked = true

[tops."Pour ceux qui aiment le jazz"]
liked = true
