plays = 2.9700724360405784
last = "2026-09-17"
weight = 1.0

[tops."Aujourd'hui maintenant"]
plays = 1.0
last = "2026-09-09"
liked = true

[tops.Deux]
liked = true

[tops."Entre voisins"]
liked = true

[tops.Essayer]
plays = 1.0
last = "2026-09-17"
liked = true

[tops."Pour ceux qui aiment le jazz"]
plays = 1.0
last = "2026-09-17"
liked = true
