plays = 4.939732782918117
last = "2026-09-14"
weight = 1.0

[tops."Anything We Want"]
plays = 1.0
last = "2026-09-10"

[tops."Get Gone"]
plays = 1.0
last = "2026-09-11"
liked = true

[tops."On The Bound"]
plays = 1.0
last = "2026-09-14"
liked = true

[tops."Paper Bag"]
plays = 1.0
last = "2026-09-11"

[tops.Shadowboxer]
plays = 1.0
last = "2026-09-08"
