plays = 3.801758027999738
last = "2026-09-25"
weight = 1.0

[tops.Brutalisme]
plays = 1.0
last = "2026-09-07"

[tops."La Fête noire"]
plays = 2.0
last = "2026-09-07"

[tops."Maddy la nuit"]
plays = 1.0
last = "2026-09-25"
liked = true
