plays = 5.781114680009411
last = "2026-09-24"
weight = 1.0

[tops."All Being Fine"]
plays = 1.941040531165702
last = "2026-09-24"
liked = true

[tops."Big Swimmer"]
plays = 1.0
last = "2026-09-10"

[tops."Milk Boy (I Love You)"]
plays = 1.0
last = "2026-09-15"

[tops."The Moods That I Get In"]
plays = 1.0
last = "2026-09-14"

[tops."This Hotel Room"]
plays = 1.0
last = "2026-09-14"
