plays = 3.0
last = "2026-09-07"
weight = 1.0

[tops.Antitaxi]
plays = 1.0
last = "2026-09-07"
liked = true

[tops."Elle ne t'aime pas"]
plays = 1.0
last = "2026-09-07"

[tops."Sur la planche"]
plays = 1.0
last = "2026-09-07"
liked = true
blacklisted = true
