plays = 2.8964457165977118
last = "2026-10-10"
weight = 1.0

[tops."Dance Yrself Clean"]
plays = 1.0
last = "2026-09-27"

[tops.Dancer]
plays = 1.0
last = "2026-09-25"

[tops."oh baby"]
plays = 1.0
last = "2026-10-10"
liked = true
