plays = 1.0
last = "2026-09-09"
weight = 1.0

[tops."Au café du canal"]
skipped = 1

[tops."Jompa Vo!"]
liked = true

[tops."Les Papets Les Minots"]
plays = 1.0
last = "2026-09-09"
liked = true

[tops.Occitanista]
liked = true

[tops."Pauvre De Nous"]
liked = true

[tops."Raja Occitani"]
liked = true
