plays = 0.0
weight = 1.0

[tops."Au café du canal"]
skipped = 1

[tops."Jompa Vo!"]
liked = true

[tops."Les Papets Les Minots"]
liked = true

[tops.Occitanista]
liked = true

[tops."Pauvre De Nous"]
liked = true

[tops."Raja Occitani"]
liked = true
