plays = 4.984879604614401
last = "2026-09-11"
weight = 1.0

[tops."All Your Sisters"]
skipped = 1

[tops."Fade Into You"]
plays = 1.9962091367899788
last = "2026-09-11"
liked = true

[tops."Into Dust"]
plays = 1.0
last = "2026-09-11"

[tops.Roseblood]
plays = 1.0
last = "2026-09-08"

[tops."She Hangs Brightly"]
plays = 1.0
last = "2026-09-11"
liked = true
