plays = 3.966395024131736
last = "2026-09-16"
weight = 1.0

[tops."Everything Goes My Way"]
plays = 1.0
last = "2026-09-07"
liked = true

[tops."Nights Out"]
plays = 1.0
last = "2026-09-16"

[tops."Radio Ladio"]
plays = 1.0
last = "2026-09-16"

[tops."The End Of You Too"]
plays = 1.0
last = "2026-09-16"
