plays = 2.9401448720811567
last = "2026-09-17"
weight = 1.0

[tops."Cette colère"]
plays = 1.0
last = "2026-09-09"
liked = true

[tops."L'enfant"]
plays = 1.0
last = "2026-09-17"
liked = true

[tops."Notre silence"]
liked = true

[tops."Une autre année"]
plays = 1.0
last = "2026-09-09"
