plays = 3.0
last = "2026-09-16"
weight = 1.0

[tops."Chaos A.D"]
plays = 1.0
last = "2026-09-16"

[tops.Listeners]

[tops.Love]
plays = 1.0
last = "2026-09-16"

[tops."The Shooter"]
plays = 1.0
last = "2026-09-16"
