plays = 5.86967855171528
last = "2026-09-27"
weight = 1.0

[tops."Chaos A.D"]
plays = 1.0
last = "2026-09-16"

[tops."Come On"]
plays = 1.0
last = "2026-09-27"
liked = true

[tops.Listeners]
plays = 1.9924326442238343
last = "2026-09-27"
liked = true

[tops.Love]
plays = 1.0
last = "2026-09-16"

[tops."The End"]
skipped = 1

[tops."The Shooter"]
plays = 1.0
last = "2026-09-16"
