plays = 2.9848652884476685
last = "2026-09-10"
weight = 1.0

[tops."Into My Arms"]
plays = 1.0
last = "2026-09-08"

[tops."Jubilee Street"]
plays = 1.0
last = "2026-09-08"

[tops."Where the Wild Roses Grow"]
plays = 1.0
last = "2026-09-10"
