plays = 2.948216019135157
last = "2026-09-25"
weight = 1.0

[tops.Civilisation]
plays = 1.0
last = "2026-09-25"

[tops."Quand est-ce que ça s'arrête"]
plays = 1.0
last = "2026-09-11"

[tops."Suicide social"]
plays = 1.0
last = "2026-09-25"
