plays = 2.0
last = "2026-09-09"
weight = 1.0

[tops."Anti-Racist Soldier (Live)"]
plays = 1.0
last = "2026-09-09"
liked = true

[tops."Music Is a Weapon"]
plays = 1.0
last = "2026-09-09"
liked = true
