plays = 4.0
last = "2026-09-25"
weight = 1.0

[tops.Boosters]
plays = 1.0
last = "2026-09-25"
liked = true

[tops."Je fume pu d'shit"]
plays = 1.0
last = "2026-09-25"

[tops."Raggalloween (La chanson pour Halloween)"]
plays = 1.0
last = "2026-09-25"

[tops."Stupeflip vite !!!"]
plays = 1.0
last = "2026-09-25"
