plays = 3.8448669145901437
last = "2026-09-28"
weight = 1.0

[tops.Breathe]
plays = 1.0
last = "2026-09-18"

[tops."Breathe (Kartell Slow Remix)"]
plays = 1.0
last = "2026-09-14"

[tops."Breathe (Kid Francescoli Remix)"]
plays = 1.0
last = "2026-09-28"

[tops.Smile]
plays = 1.0
last = "2026-09-10"
