plays = 4.818204316842349
last = "2026-09-23"
weight = 1.4285714626312256

[tops."Come Together"]
plays = 1.0
last = "2026-09-13"

[tops."Eleanor Rigby"]
plays = 1.0
last = "2026-09-10"

[tops."Here Comes the Sun"]
plays = 1.0
last = "2026-09-10"

[tops."Strawberry Fields Forever"]
plays = 1.0
last = "2026-09-10"

[tops."Tomorrow Never Knows"]
plays = 1.0
last = "2026-09-23"
