plays = 23.56626665744953
last = "2026-10-05"
weight = 1.4285714626312256

[tops."Come Together"]
plays = 1.9554462206115173
last = "2026-09-25"

[tops."Day Tripper (Take 1 - Instrumental Backing Track)"]
plays = 1.0
last = "2026-10-05"

[tops."Day Tripper (Takes 2 And 3 - Instrumental Backing Track)"]
plays = 1.0
last = "2026-10-05"

[tops."Day Tripper [Songwriting Work Tape]"]
plays = 1.0
last = "2026-10-05"

[tops."Drive My Car (Takes 1 And 2 - Instrumental Backing Track)"]
plays = 1.0
last = "2026-10-05"

[tops."Eleanor Rigby"]
plays = 1.0
last = "2026-09-10"

[tops."For No One - 2022 Mix"]
plays = 1.0
last = "2026-10-05"

[tops."Here Comes the Sun"]
plays = 1.0
last = "2026-09-10"

[tops."I'm Looking Through You (First Version - Take 1)"]
plays = 1.0
last = "2026-10-05"

[tops."I'm Looking Through You (Second Version - Take 2)"]
plays = 1.0
last = "2026-10-05"

[tops."If I Needed Someone (Take 1 - Instrumental Backing Track)"]
plays = 1.0
last = "2026-10-05"

[tops."Norwegian Wood (This Bird Has Flown) [First Version - Take 1]"]
plays = 1.0
last = "2026-10-05"

[tops."Norwegian Wood (This Bird Has Flown) [Second Version - Take 2]"]
plays = 1.0
last = "2026-10-05"

[tops."Norwegian Wood (This Bird Has Flown) [Third Version - Take 3]"]
plays = 1.0
last = "2026-10-05"

[tops."Nowhere Man (Second Version - Take 5 - Instrumental Backing Track)"]
plays = 1.0
last = "2026-10-05"

[tops."Run For Your Life (Takes 1-5 - Instrumental Backing Track)"]
plays = 1.0
last = "2026-10-05"

[tops."Strawberry Fields Forever"]
plays = 1.9094168868248205
last = "2026-10-05"

[tops."Till There Was You - Remastered 2009"]
plays = 1.0
last = "2026-10-05"

[tops."Tomorrow Never Knows"]
plays = 1.0
last = "2026-09-23"

[tops."Wait (Take 3 - Instrumental Backing Track)"]
plays = 1.0
last = "2026-10-05"

[tops."We Can Work It Out (Paul's Demo)"]
plays = 1.0
last = "2026-10-05"

[tops."We Can Work It Out (Take 1 - Instrumental Backing Track)"]
plays = 1.0
last = "2026-10-05"

[connections]
arthur-satan = 3
